version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
- cmd: dotnet tool install -g dotnet-sonarscanner
- cmd: dotnet sonarscanner begin /d:/menueplaner/"menuplaner" /d:"TheKeiler_MenuPlaner" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.branch.name=%APPVEYOR_REPO_BRANCH% /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="TheKeiler_MenuPlaner" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="CoverageResults\coverage.opencover.xml"
build_script:
- cmd: dotnet build MenuPlanerApp.Core\MenuPlanerApp.Core.csproj
- cmd: dotnet build MenuPlanerApp.Core.Tests\MenuPlanerApp.Core.Tests.csproj
- cmd: dotnet test MenuPlanerApp\MenuPlanerApp.Core.Tests\MenuPlanerApp.Core.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput="../CoverageResults/" 

after_build:
- cmd: dotnet sonarscanner end /d:sonar.login="TheKeiler_MenuPlaner"