version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_build:
- cmd: nuget restore C:\projects\menuplaner\MenuPlanerApp\MenuPlanerApp.sln
- cmd: dotnet tool install -g dotnet-sonarscanner
- cmd: dotnet sonarscanner begin /k:"TheKeiler_MenuPlaner" /o:"thekeiler" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.branch.name=%APPVEYOR_REPO_BRANCH% /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="183525949e759d3a3afd2be01711ca9acb7a8ec0" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="CoverageResults\coverage.opencover.xml"

build_script:
- cmd: msbuild /t:restore MenuPlanerApp\MenuPlanerApp.sln
- cmd: dotnet test MenuPlanerApp\MenuPlanerApp.Core.Tests\MenuPlanerApp.Core.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput="../CoverageResults/" 
- cmd: dotnet test MenuPlanerApp\MenuPlanerApp.API.Tests\MenuPlanerApp.API.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput="../CoverageResults/" /p:MergeWith="../CoverageResults/coverage.json"  
- cmd: dotnet test MenuPlanerApp\MenuPlanerApp.Tests\MenuPlanerApp.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput="../CoverageResults/" /p:MergeWith="../CoverageResults/coverage.json" /p:CoverletOutputFormat=opencover

after_build:
- cmd: dotnet sonarscanner end /d:sonar.login="183525949e759d3a3afd2be01711ca9acb7a8ec0"